const PALAVRAS_PESSOA = [
  "pessoa",
  "pessoas",
  "mulher",
  "mulheres",
  "homem",
  "homens",
  "menina",
  "meninas",
  "menino",
  "meninos",
  "crianca",
  "criança",
  "criancas",
  "crianças",
  "casal",
  "familia",
  "família",
  "modelo",
  "modelos",
  "figura humana",
  "figuras humanas",
  "morador",
  "moradora",
  "moradores",
  "cliente",
  "clientes",
  "sentad",
  "deitad",
  "de pé",
  "em pé",
  "parad",
  "lendo",
  "lendo um livro",
  "tomando",
  "person",
  "people",
  "woman",
  "man",
  "child",
  "children",
  "family",
  "couple",
  "sitting",
  "standing",
  "lying",
];

// Só decide se injeta o bloco "HUMAN SCALE" no system_flash (render normal)
// ou qual caminho seguir no refinamento — não tenta validar/filtrar conteúdo.
export function detectarPedidoPessoa(prompt: string): boolean {
  const texto = prompt.toLowerCase();
  return PALAVRAS_PESSOA.some((palavra) => texto.includes(palavra));
}
