import type { Mood } from "../tipos";

// Seção 6.4 — bloco de atmosfera pela janela, por mood.
export function atmosferaMood(hora: Mood | "", temDirecaoDoUsuario: boolean): string {
  const escape = temDirecaoDoUsuario
    ? " — UNLESS the user direction explicitly requests a different sky/background."
    : ".";

  switch (hora) {
    case "noite":
      return `BACKGROUND THROUGH WINDOWS (must match nighttime mood):
- The sky visible through every window must be DARK — deep navy to near-black, with realistic night atmosphere. NOT grey, NOT pale, NOT daytime.
- If buildings, skyline, or urban context are visible through the glass (modeled in SketchUp OR generated by you), they appear as DARK SILHOUETTES with scattered warm interior lights glowing in their windows — typical Brazilian/urban nighttime cityscape.
- If the SketchUp viewport shows only a neutral grey/flat background through the windows (no modeled exterior), you have FREEDOM to paint a coherent nighttime scene: dark sky, distant city lights, soft urban glow on the horizon. Keep it simple and editorial — no neon clutter, no excessive lighting, just believable night.
- Distant vegetation (if any) appears as dark silhouettes against the sky, NOT brightly lit.
- The exterior must NEVER appear daytime or pale grey — that would break the night atmosphere of the interior${escape}`;
    case "blue hour":
      return `BACKGROUND THROUGH WINDOWS (must match blue-hour mood):
- The sky visible through every window must show TWILIGHT TRANSITION — deep blue gradient at top fading to soft purple/lavender near the horizon. NOT grey, NOT bright daytime, NOT pitch black.
- If buildings or urban context are visible (modeled OR generated), they appear as SOFT SILHOUETTES with some warm interior lights starting to glow — that magic moment just after sunset.
- If the SketchUp viewport shows only a neutral grey background through the windows, you have FREEDOM to paint a coherent blue-hour scene: deep blue sky gradient, faint city lights beginning to appear, soft purple horizon glow.
- Distant vegetation appears as dark silhouettes catching the last cool light${escape}`;
    case "sem luz natural":
      return `BACKGROUND THROUGH WINDOWS (no natural light):
- The exterior visible through windows must appear COMPLETELY DARK or near-black — like deep night with no atmospheric light. Windows read as dark voids.
- If buildings are visible, they are very dark silhouettes with a few isolated warm interior lights — minimal exterior detail.
- Do NOT show daytime sky, grey horizon, or any pale tone outside — this is a fully artificial-lit interior scene${escape}`;
    case "golden hour":
      return `BACKGROUND THROUGH WINDOWS (must match golden-hour mood):
- The sky visible through every window must show GOLDEN-HOUR ATMOSPHERE — warm yellow-orange gradient at horizon transitioning to soft pink/peach above, fading to light blue at the top. NOT flat grey, NOT noon-bright.
- If buildings or urban context are visible (modeled OR generated), they catch warm golden light on their facades, with long soft shadows. Distant buildings show warmth from the setting sun on their west-facing sides.
- If the SketchUp viewport shows only a neutral grey background through the windows, you have FREEDOM to paint a coherent golden-hour scene: warm sky gradient, distant treetops or buildings bathed in late-afternoon sunlight.
- Distant vegetation is warmly lit, foliage edges glowing${escape}`;
    case "fim do dia":
      return `BACKGROUND THROUGH WINDOWS (must match late-afternoon mood):
- The sky visible through every window shows LATE-AFTERNOON GLOW — soft pink, peach and pale orange near the horizon, sky lower in contrast than at noon. Not yet sunset, but light is clearly waning.
- If buildings or context are visible, they show soft directional warm light from the low sun, with long gentle shadows.
- If only a neutral grey background is visible, paint a coherent fim-de-dia atmosphere: soft warm sky gradient, distant scenery softly lit${escape}`;
    case "overcast":
      return `BACKGROUND THROUGH WINDOWS (must match overcast mood):
- The sky visible through every window must be FLAT GREY OVERCAST — uniform cloud cover, no sun, no blue patches, no warmth. Slightly muted and desaturated.
- Buildings or context (if visible) appear under flat diffused light, no harsh shadows, slightly desaturated colors.
- If the viewport shows only neutral grey background, you can leave it as cloudy overcast sky — match the existing neutrality${escape}`;
    case "luz difusa":
      return `BACKGROUND THROUGH WINDOWS (soft diffused daylight):
- The sky visible through every window is SOFT OVERCAST or hazy bright — uniform pale light, no strong sun, no deep shadows. Subtle warmth allowed but not direct sunlight.
- Buildings or context (if visible) appear evenly lit, no harsh contrast${escape}`;
    case "meio-dia":
    case "ceu brasileiro":
      return `BACKGROUND THROUGH WINDOWS (must match bright daylight mood):
- The sky visible through every window must be VIVID BRIGHT BLUE with strong daylight, typical Brazilian clear sky.
- Buildings or context (if visible) are brightly lit, crisp shadows, vibrant colors.
- If only a neutral grey background is visible, paint a coherent clear-sky daytime scene${escape}`;
    case "luz marcada":
      return `BACKGROUND THROUGH WINDOWS (must match strong midday light):
- The sky visible through every window is BRIGHT BLUE with strong direct sunlight.
- Buildings or context (if visible) catch sharp directional shadows from overhead sun${escape}`;
    default:
      return `BACKGROUND THROUGH WINDOWS (must match the daytime mood):
- The sky visible through every window shows SOFT DAYTIME — clear blue with soft white clouds, or warm late-afternoon depending on the mood. NOT flat grey, NOT dark.
- Buildings or context (if visible) are naturally lit by the daylight described above.
- If only a neutral grey background is visible in the SketchUp viewport, you have FREEDOM to paint a coherent daytime scene with appropriate sky and distant scenery${escape}`;
  }
}

const MOODS_QUE_LIBERAM_FUNDO: (Mood | "")[] = ["noite", "blue hour", "golden hour", "fim do dia", "sem luz natural"];

// Seção 6.5
export function liberaFundoAtmosferico(hora: Mood | ""): boolean {
  return MOODS_QUE_LIBERAM_FUNDO.includes(hora);
}

export function regraSkyline(hora: Mood | ""): string {
  if (liberaFundoAtmosferico(hora)) {
    return `- FAILURE 4 — IGNORING ATMOSPHERIC MOOD ON THE EXTERIOR: the chosen mood is '${hora}'. The exterior visible through every window MUST follow the atmospheric description in the ATMOSPHERIC BACKGROUND block below (sky color, distant buildings with lights, urban silhouettes, etc — appropriate to '${hora}'). The SketchUp viewport's flat grey background is NOT a 'clean sky' to preserve — it is a placeholder that you must replace with a coherent atmospheric scene matching the mood. You ARE allowed to add distant buildings, city silhouettes, sky gradient, and atmospheric context that match the mood. The Brazilian-contemporary night scene with dark buildings and warm window lights is the desired result, NOT a black/grey void.`;
  }
  return `- FAILURE 4 — INVENTING SKYLINE / CONTEXT: if the input shows clean sky, empty void, or no buildings visible through windows, the output MUST show the same. DO NOT add urban skylines, distant buildings, mountains, forests, or any context that is not modeled in the input. Empty background is the correct result.`;
}
